# Zuul网关基础配置
zuul:
  routes:
    # 配置路由规则，将 /test/** 的请求转发到 test-service 服务中
    test:
      path: /test/**
      serviceId: test-service
  prefix: /zuul

# 服务注册中心相关配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/